### ISSUE TITLE
Warning regarding future deprecation when running with Java 11

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#121]
With Java 11:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by edu.mit.csail.sdg.alloy4whole.SimpleGUI (file:/home/dchemoui/LOCAL/electrum2.0.1.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of edu.mit.csail.sdg.alloy4whole.SimpleGUI
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by pkriens** [comment]
Alloy is Java 8

**Comment by grayswandyr** [comment]
I don't follow Java versions particularly but here I'm only running the JAR, not compiling it. Wouldn't it be possible to have a compiled versions that runs in all Java versions starting at a certain version? Otherwise some users may experience problems, I guess.

**Comment by pkriens** [comment]
Yes, but this requires work ...  we need to fix all access to the `Method.setAccessible()` method. 

Since Java 9, they introduced a silly module system that makes it impossible to get rid of these warnings and one of the next Javas is going to deny it :-( It is a fundamental confusion between access and security that has plagued Java from the start.

When we integrate Electrum and I've got some time then I can fix it. Or if you have a volunteer?
