### ISSUE TITLE
Cardinality of Int

### ISSUE THREAD

**Issue by pkriens** [AlloyTools/org.alloytools.alloy#130]
While playing with the Evaluator I noticed that `#Int = 0`.  This seems to also have some effect on the model since:

     run { # Int > 0 }

Does not provide an instance

**Comment by aleksandarmilicevic** [comment]
That's because `#Int` is always `0`!  (mind blowing)

In Alloy, instead of specifying individual int atoms, only a bitwidth is specified.  When the specified bitwidth is `b`, the `Int` set becomes <img src="https://render.githubusercontent.com/render/math?math=\{-2^{(b-1)},\ldots,2^{(b-1)}%20-%201\}"/>. The cardinality of that set is <img src="https://render.githubusercontent.com/render/math?math=2^b"/>.

1. With the "Prevent Overflows" option turned off (i.e., using the wraparound semantics)
  - `#Int` is `2^b`, which is exactly `0` when integers wrap around, thus `#Int > 0` is unsatisfiable
2. With the "Prevent Overflows" option turned on
  - `#Int` is `2^b`, which clearly overflows, and so `#Int > 0` is unsatisfiable
  - if you already have an instance and then in the evaluator evaluate `#Int`, the evaluator will print out `0` and say that overflow happened.

**Comment by pkriens** [comment]
stupid of me ...
