### ISSUE TITLE
Fix and improve meta capabilities

### ISSUE THREAD

**Issue by grayswandyr** [AlloyTools/org.alloytools.alloy#194]
The [meta capability system is broken in Alloy 6](#174). In addition to fixing it, it would be very useful to improve the system, at the very least by providing such capabilities for var and non-var stuff.

**Comment by nmacedo** [comment]
I've fixed this and added additional meta-sigs, `ssig$` and `vsig$` for static and mutable sigs, respectively, and likewise for fields with `sfield$` and `vfield$`. Names are temporary, let me know your suggestions (and whether I should add anything else).

**Comment by nmacedo** [comment]
- Yes, I thought of using `static` and `var` prefixes but also felt it would be too long.

- Sure, I can add the `var$` and `static$` macros. By the way, the `sig$` and `field$` are now defined simply as macros `ssig$ + vsig$`, and `sfield$ + vfield$`, respectively.
 
- Glad you brought up the documentation, because there's actually another field defined in the code that is not documented, the `parent` of a signature. I don't know why it's been excluded from the documentation, but it is available in the standard distribution.

**Comment by nmacedo** [comment]
Done, there are now sigs `static$` and `var$` for the static and mutable elements, respectively. Variants of `sig$` and `field$` were removed, they can be obtained by intersecting with the new sigs (e.g., `sig$ & var$` for the mutable sigs, `field$ & static$` for the static fields).
