### ISSUE TITLE
Inconsistent behavior for running the same predicate

### ISSUE THREAD

**Issue by kaiyuanw** [AlloyTools/org.alloytools.alloy#20]
This issue is found in Alloy4.2 with SAT4J solver.

For example, I have the following Alloy model that models a directed tree:
```Alloy
module dtree
sig Node {
  edges: set Node
}
pred isDirectedTree {
  -- acyclic:
  no iden & ^edges
  -- injective: with mutation of the correct formula "edges.~edges in iden"
  edges.~edges != iden 
  -- connected:
  (Node -> Node) in ^(edges + ~edges)
}
```
If I run the following test
```Alloy
pred test {
  no Node
  no edges
  isDirectedTree[]
}
run test for 4
```
together with the model in side a single file (dtree.als), I got no instance with 439 vars. 20 primary vars. 636 clauses.

However, if I save the test in a separate file (test.als) and open the dtree module as shown below:
```Alloy
open dtree
pred test {
  no Node
  no edges
  isDirectedTree[]
}
run test for 4
```
I got an instance found with 449 vars. 24 primary vars. 642 clauses.  When I inspect the instances, I found that the univ set = {Univ$0, ...} and all other sets are empty.  I have no idea where do those Univ$i come from and I think separating the test predicate to a different file should behave the same as it is in the same file with the model.  Please clarify or correct the behavior.

**Comment by hwayne** [comment]
Looks like the following spec also passes:

```
run {}
```

It seems that there must always be a signature in the top level file, and if there isn't any, it defaults to `this/Univ`. Same doesn't hold true for importing, so importing a file with not signatures doesn't add `foo/Univ`.

**Comment by aleksandarmilicevic** [comment]
First, given `no Node and no edges`, lets see when `isDirectedTree` is true and when it's false.
* the "acyclic" constraint is always satisfied (since `edges` is empty)
  ```alloy
   // acyclic:
  no iden & ^edges
  ```
* the "connected" constraint is always satisfied since `Node->Node` is empty and `^(edges + ~edges)` is empty
  ```alloy
  // connected:
  (Node -> Node) in ^(edges + ~edges)
  ```
* the "injective" constraint depends on the content of `iden`
  ```alloy
  // injective: with mutation of the correct formula "edges.~edges in iden"
  edges.~edges != iden
  ```
  * when `iden` is empty (which is IFF `univ` is empty), the constraint is `false` (making the whole predicate UNSAT)
  * when `iden` is non-empty (which is IFF `univ` is non-empty), the constraint is `true` (making the whole predicate SAT).

So, whether your model is SAT or UNSAT really comes down to whether the universe is empty or not.  

Regardless of all that, I agree that whatever the behavior is, it should be the same regardless of whether you put the test predicate in the same or in a different file.

As you pointed out, something funny is happening with module imports in Alloy4.2 causing some ghost `Univ$i` atoms to get added to the universe.  Leaving aside the question "why" that happens, I hope it at least explains why the model is UNSAT in one case and SAT in the other.

Now, I don't remember from the top of my head why those ghost atoms used to be added.  I tried your example with Alloy5 and I got consistent behavior in both cases.  First, I tried it without explicitly specifying the scope (e.g., just with `run test`) in which case the model was SAT in both cases because (for who know what reason) integers were automatically added to the universe in both cases.  Next, I explicitly set the scope of integers to 0 (e.g., `run test for 0 Int`), and the model was UNSAT in both cases (because the universe was empty).

**Comment by pkriens** [comment]
Not sure this should be closed? You indicate:

Regardless of all that, I agree that whatever the behavior is, it should be the same regardless of whether you put the test predicate in the same or in a different file.

> As you pointed out, something funny is happening with module imports in Alloy4.2 causing some ghost Univ$i atoms to get added to the universe. Leaving aside the question "why" that happens, I hope it at least explains why the model is UNSAT in one case and SAT in the other.

This seems wrong behavior. Ok to move it to abeyance but feel uncomfortable to close this since people will not find this as an open issue?

**Comment by aleksandarmilicevic** [comment]
Closed because of this:

> I tried your example with Alloy5 and I got consistent behavior in both cases. 

and not because of what you quoted.

**Comment by pkriens** [comment]
So this problem does not exist anymore?
