### ISSUE TITLE
4.2_2015-02-22 does not find a counterexample

### ISSUE THREAD

**Issue by hwayne** [AlloyTools/org.alloytools.alloy#24]
Discovered [here](https://stackoverflow.com/questions/47609392/how-can-a-imply-b-and-b-imply-a-and-yet-a-and-b-are-not-equivalent/47612275?noredirect=1#comment82228081_47612275).

```alloy
one sig PositiveEven {
     elements: set Int 
}

pred defining_property {
    PositiveEven.elements = {i: Int | i >= 0 and (rem[i,2] = 0)}
}

pred generate_set_members {
    0 in PositiveEven.elements
    all i: PositiveEven.elements - 0 | i.minus[2] in PositiveEven.elements
    // Create a complete set of positive even elements
    all i: Int | i.minus[2] in PositiveEven.elements => i in PositiveEven.elements
}

assert equivalent_constraints {
    generate_set_members => defining_property
}

check equivalent_constraints
```

On Windows 10, 4.2 finds a counterexample but 4.2_2015-02-22 does not. Both versions produce the same Kodkod under "Sat Solver > Output Kodkod to File", but different CNFs under "Sat Solver > Output CNF to File".

Since this repo doesn't have the complete repo history of alloy, I used [this](https://github.com/osiire/AlloyAnalyzer/tree/f9b8f786b456a0fcfa46bfdf664f7c0d006c5173) commit as a copy of 4.2 and [this](https://github.com/osiire/AlloyAnalyzer/tree/312365a6cfe2cdd0b922274cc667475b43c65f23) as 4.2_2015. My  _guess_ is that the issue is somewhere in fol2sat, possibly no earlier than [Translator.java](https://github.com/osiire/AlloyAnalyzer/tree/f9b8f786b456a0fcfa46bfdf664f7c0d006c5173/kodkod/engine/fol2sat).* But I haven't built this from source to check because I, uh, don't actually know Java :( For the same reason, I haven't checked whether or not this is still a bug in master.

*My reasoning is that "Output CNF" constructs the Kodkod just like "Output Kodkod" does, but "Output CNF" also makes a call to Translator.

**Comment by pkriens** [comment]
I think this has to do with the Integer overflow handling. @aleksandarmilicevic  should be able to throw some light on this.

**Comment by hwayne** [comment]
I wrote a new spec to check if it's Integer overflow:

```alloy
one sig PositiveEven {
     elements: set Int 
}

pred defining_property {
    PositiveEven.elements = {i: Int | i >= 0 and (rem[i,2] = 0)}
}

pred generate_set_members {
    0 in PositiveEven.elements
    all i: PositiveEven.elements - 0 | i.prev.prev in PositiveEven.elements
    // Create a complete set of positive even elements
    all i: Int | i.prev.prev in PositiveEven.elements => i in PositiveEven.elements
}

assert equivalent_constraints {
    generate_set_members => defining_property
}

check equivalent_constraints
```

The only difference is that I replaced all instances of `i.minus[2]` with `i.prev.prev`. Both versions of Alloy generated the same CNF in this version of the spec. This suggests it has something to do with overflows.

**Comment by pkriens** [comment]
Yes, there is another problem with integer overflow as well. If you use seq then you **must** specify a bit width. 
The Kodkod coding for integer overflow was optimised and I think something went wrong. 

I still do not see how this tests what is supposed to test? If I encode it like this I do not get a counter example?

     pred generate_set_members {
       0 in PositiveEven.elements
       all i: Int |  i.prev.prev >= 0 and i.prev.prev in PositiveEven.elements <=> i in PositiveEven.elements
     }

I am also uncomfortable with the 'architecture' of this specification. It uses 'global' variables and they always make me itch. I also think that the => in in PositiveEven.elements should be a <=>?

I think the following is a more concise version of what is attempted (but I've been wrong before):
        
        let defining_property = {i: Int | i >= 0 and (rem[i,2] = 0)}
        
        pred generate_set_members[ s : set Int ] {
            0 in s and
            all i: Int | let v = i.prev.prev | v >= 0 and v in s <=> i in s
        }        

        assert equivalent_constraints {
            all s : set Int | generate_set_members[s] <=> s = defining_property
        }        
        check equivalent_constraints

**Comment by pkriens** [comment]
Yeah, but I hate finding the optimal tool for each problem. I am trying to see if I can help moving Java developers to formal tool, which would be a big gain for the world. I settle for 'good enough' if I can use the same syntax and tool instead of forcing people to learn different syntaxes for similar tasks.

**Comment by aleksandarmilicevic** [comment]
It doesn't find a counter example because, mathematically speaking, there is no counterexample, in your model!  

The counterexample found by Alloy4.2 is spurious and it arises exactly because of the wraparound integer semantics.  The "no overflows" semantics is intended to fix exactly that problem, so that Alloy can be used to model check specs against the mathematical definitions of arithmetic operations; if you want the wraparound semantics, you should turn off overflow prevention (from the main menu, click `Options` -> `Prevent Overflows`).

Concretely, this is your `generate_set_members` predicate:
```
pred generate_set_members {
    0 in PositiveEven.elements
    all i: PositiveEven.elements - 0 | i.minus[2] in PositiveEven.elements
    // Create a complete set of positive even elements
    all i: Int | i.minus[2] in PositiveEven.elements => i in PositiveEven.elements
}
```
As you say in the comment there, it should generate only positive even numbers.  And that is true: when you add `0` and then keep adding all integers `i` such that `i-2` is positive and even, you will end up with positive even numbers.  

Now, let's check what Alloy thinks about that.  If you run
```
run generate_set_members for 3 Int
```
with Alloy4.2 (no overflow prevention) you get `[-4, -2, 0, 2]`, and with a newer Alloy with overflow prevention set to true, you get `[0, 2]`.  The reason why you get those negative numbers with Alloy4.2 is because `-4 - 2` equals `2`, and since `2` is positive and even it concludes that `-4` must be positive and even.

Executing
```
run defining_property for 3 Int
```
in both cases returns `[0, 2]`, hence, Alloy4.2 reports a bogus counter example, and the newer Alloy doesn't.
