### ISSUE TITLE
Function chaining seems broken

### ISSUE THREAD

**Issue by EugeneWagner** [AlloyTools/org.alloytools.alloy#47]
The "add" function in the following simple model doesn't work consistently if it's chained (see assertion "addWorksFluently") but works fine without chaining (see assertion "addWorks")

```alloy
sig IntSet{
   values: set Int
}

fun IntSet.add(value: Int): IntSet {
   { result: one IntSet | result.values = this.values + value }
}

fun emptySet: IntSet {
   { result: IntSet | no result.values }
}

assert emptySetWorks{
   all myIntSet: IntSet |
      myIntSet = emptySet implies no myIntSet.values and myIntSet.values = none
}
check emptySetWorks

assert addWorks {
   all disj s1, s2: IntSet |
      s1 = emptySet.add[0] and
      s2 = s1.add[1]
      implies
      s1.values = 0 and
      s2.values = 0 + 1
}
check addWorks

assert addWorksFluently {
   all disj s: IntSet |
      s = emptySet.add[0].add[1]
      implies
      s.values = 0 + 1
}
check addWorksFluently
````

**Comment by aleksandarmilicevic** [comment]
I wanted to clarify one point: this behavior has absolutely **nothing to do with functions** in Alloy.

To prove it, you can rewrite your `addWorksFluently` to not use functions at all (by manually inlining them, which is what Alloy does behind the scenes anyway), and you'll get exactly the same behavior:
```alloy
check addWorksFluently {
  all s: IntSet |
    s = {result2: IntSet | result2.values = {result1: IntSet | result1.values = { result0: one IntSet | no result0.values }.values + 0}.values + 1}
    implies
    s.values = 0 + 1
}
```

This has everything to do with **set comprehension**.  Set comprehension, by definition, evaluates to a set of atoms/tuples that satisfy a given predicate.  The `add` function uses set comprehension to compute all `IntSet` atoms whose `values` field contains all values in `this` plus a given integer: if there is no such `IntSet` atom in the universe, the result will be an empty set.  There is no Alloy black magic going on there.  So far, this is just the most fundamental, unaltered predicate logic.

What can be confusing is the meaning of `all s: IntSet | ...`.  It's very intuitive to think that this must mean "for all integer sets" just because the name says so.  But in fact, `IntSet` is defined as a sig, so it is treated just like any other set.  Since your `check` command doesn't specify a scope, the default scope of 3 is used, meaning that Alloy will consider all possible `IntSet` sets of up to only 3 elements.  Since there are no additional facts specified in the model, there are no restrictions for the `values` field, so Alloy can consider an instance consisting of, say, 2 `IntSet` atoms, both having their `values` field set to `{2, 4}`.  Against that instance, `emptySet` evaluates to `none`, `emptySet.add[0]` also evaluates to `none`, and `emptySet.add[2]` evaluates to `none` too.

To check that chaining function calls indeed works, you could add a fact like this to your model:
```alloy
fact { 
  some s0, s1, s2: IntSet | no s0.values && s1.values = 0 && s2.values = 1
}
```
which would make your `addWorksFluently` true.  

More generally, you could add a fact to ensure that there exists an `IntSet` atom corresponding to every possible int set, and then check a more general version of `addWorksFluently`:
```alloy
fact ensureIntSetAtoms {
  all is: set Int | some s: IntSet | s.values = is
}

check addWorksFluently {
  all s: IntSet |
    all i, j: Int |
      s = emptySet.add[i].add[j]
      iff
      s.values = i + j
} for 0 but 2 Int, exactly 16 IntSet
```
This model, however, is higher-order, so you'd have to use [Alloy*](https://github.com/aleksandarmilicevic/hola/releases/tag/v0.3_2018-04-14) to check that this assertion is indeed true.

Yes, this is an important topic and a common pitfall, but it is not an issue in the sense that Alloy can be changed in any way that would help accommodate it.

**Comment by aleksandarmilicevic** [comment]
We could, however, create a section in our Wiki and move this example there.
