### ISSUE TITLE
no instances in a counterexample

### ISSUE THREAD

**Issue by arademaker** [AlloyTools/org.alloytools.alloy#94]
See https://stackoverflow.com/questions/58147352/show-counterexample-in-alloy/58156811#58156811

**Comment by dnjackson** [comment]
Hi Alexandre,

I ran your model for you. There is an instance. Notice that it says "Due to your theme settings, every atom is hidden. Please click Theme and adjust your settings". This means that an instance is being shown, and that if it contains any atoms, they're not shown because of the theme that customizes the visualization. In this case, it's because unconnected integers are not shown in the default theme. You can see the instance either by viewing it in a different way (any of the other options -- Txt, Table, Tree), or by changing the theme.

Daniel

**Comment by arademaker** [comment]
Thank you @dnjackson, but if I asked for the Txt or Tree view, I only get empty models. 

<img width="991" alt="image" src="https://user-images.githubusercontent.com/86403/66258107-ae207d00-e777-11e9-9930-01b1c6befe87.png">

**Comment by aleksandarmilicevic** [comment]
An empty model is still an instance. (in which your "all p: Value | ..."
assertion trivially holds)

If you want to disallow empty models, add "some Value" to your assertion.

**Comment by hwayne** [comment]
The empty model _is_ a counterexample to the statement 

```  
  (all x: Value | p [x]) iff (some x: Value | p [x]) 
```

`(∀ x ∈ {}: F) /\ !(∃ x ∈ {}: F)` is a counterexample to your assertion.

**Comment by pkriens** [comment]
thinks this was answered ?
